import { ChurchSettings } from './types';

export const initialChurchData: ChurchSettings = {
  churchName: "",
  logoPrefix: "",
  logoSuffix: "",
  logoImageUrl: "",
  churchMotto: "",
  churchAbout: "",
  phone: "",
  whatsappNumber: "",
  whatsappMessage: "",
  email: "",
  address: "",
  cityCountry: "",
  worshipSchedule: [],
  socialLinks: [],
  coordinations: [],
  currentActivity: {
    id: "act-main",
    name: "",
    subtitle: "",
    badge: "",
    heroEyebrow: "",
    description: "",
    theme: "",
    themeVerse: "",
    date: "",
    formattedDate: "",
    time: "",
    location: "",
    address: "",
    organization: "",
    targetAudience: "",
    goal: "",
    importantNotes: "",
    pastors: [],
    heroVideo: "",
    videoPromoUrl: "",
    ctaButtonText: "",
    ctaButtonLink: "",
    countdownTarget: "",
  },
  highlights: [],
  photos: [],
  videos: [],
  upcomingEvents: [],
  testimonies: [],
  developedBy: {
    name: "Baobá Universe",
    description: "Soluções Digitais e Desenvolvimento Web de Alto Impacto",
    url: "https://baobauniverse.com"
  },
  editTimestamp: 1,
  lastUpdatedAt: "2026-08-31T00:00:00.000Z"
};

